### ISSUE TITLE
Интерфейс приложения

### ISSUE THREAD

**Issue by truenorthpaul** [Snez0K/TitleCapitalizationTool#11]
Интерфейс приложения не соответствует требованиям.

**Comment by truenorthpaul** [comment]
Интерфейс приложения должен в точности соответствовать описанному в задании.

**Comment by Snez0K** [comment]
Done

**Comment by truenorthpaul** [comment]
Некорректные цвета при выводе

**Comment by truenorthpaul** [comment]
Строка "Capitalized title:" выводится белым цветом, а должна серым (цвет вывода по умолчанию).

**Comment by truenorthpaul** [comment]
Согласно задания между вводом строк должна быть пустая строка и не должна выводиться надпись "Press enter key to continue . . . ".

**Comment by truenorthpaul** [comment]
Некорректные цвета при выводе.
