### ISSUE TITLE
Ввод пустой строки

### ISSUE THREAD

**Issue by truenorthpaul** [Snez0K/TitleCapitalizationTool#21]
При вводе пустой строки приложение работает не согласно заданию.

**Comment by truenorthpaul** [comment]
При вводе пустой строки очищается весь экран. Такого быть не должно. Если до этого вводились какие-то строки, то они затираются.

**Comment by truenorthpaul** [comment]
При вводе пустой строки курсор ввода не должен смещаться.

**Comment by Snez0K** [comment]
гуглил долго, ответа не нашел, сделал что мог. Нету инфы как сделать так чтоб курсор оставался на месте

**Comment by truenorthpaul** [comment]
Ничего не изменилось.

**Comment by Snez0K** [comment]
Прошу помощи, понятия не имею как это сделать без костылей и лишнего кода

**Comment by Snez0K** [comment]
@PavelDubsky
