### ISSUE TITLE
Перевод первого и последнего слова в соответствующий регистр

### ISSUE THREAD

**Issue by truenorthpaul** [Snez0K/TitleCapitalizationTool#25]
Первое и последнее слово переводится полностью в ниний регистр, если оно является словом-исключением.

**Comment by Snez0K** [comment]
https://youtu.be/eAoHdVTvxMo

**Comment by Snez0K** [comment]
@PavelDubsky https://youtu.be/eAoHdVTvxMo

**Comment by truenorthpaul** [comment]
Если строка начинается с пробелов, первое слово не переводится в верхний регистр, если оно является словом-исключением.
