### ISSUE TITLE
Позиционирование знаков препинания

### ISSUE THREAD

**Issue by truenorthpaul** [Snez0K/TitleCapitalizationTool#9]
Не учитываются требования приложения к знакам препинания.

**Comment by Snez0K** [comment]
Нужно проверить, подойдет так ?

**Comment by PavelDubsky** [comment]
Нет, некоторые строки из примеров в техническом задании не работают.

**Comment by truenorthpaul** [comment]
Нет, некоторые строки из примеров в техническом задании не работают.

**Comment by truenorthpaul** [comment]
Не обрабатывается тире.

**Comment by truenorthpaul** [comment]
Все еще не обрабатывается тире.
